### ISSUE TITLE
conda env dependency versioning

### ISSUE THREAD

**Issue by JenkeScheen** [XinhaoLi74/MolPMoFiT#4]
Hi,

Could you please push a conda .yml that includes versioning? I'm trying to reproduce your work but I'm running into a range of versioning issues, primarily in fastai (which seems to have had some major refactoring over the last year or so).

**Comment by XinhaoLi74** [comment]
Hi,
Done. This project uses fastai v1.

**Comment by JenkeScheen** [comment]
thanks!
