### ISSUE TITLE
Can you share a notebook how to use the ChEMBL_1M Atom model

### ISSUE THREAD

**Issue by abhik1368** [XinhaoLi74/MolPMoFiT#5]
Hi thanks for the sharing the code and workflow . Could you share how to use the ChEMBL_1M Atom model on the regression task to predict new molecules ? I am getting a vocab kind of error at my end on BBBP data . It has 48 vocabs and chembl have 80 . I would appreciate your feedback.

Sincerely
Abhik

**Comment by XinhaoLi74** [comment]
Hi Abhik, 
For using the pre-trained model, you need to use the pre-trained vocab when you build the `databunch`. Please see the [05_Pretrained_Moldes.ipynb](https://github.com/XinhaoLi74/MolPMoFiT/blob/master/notebooks/05_Pretrained_Models.ipynb). This will ensure the QSAR model use the same vocab.

For regression task, just need to change the `metric` to [r2_score, root_mean_squared_error] in the `text_classifier_learner`.
